
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CONTENT GARBAGE OPENDATA OPENDIV OPENHEADER OPENHREF OPENROW OPENSPAN OPENSTYLE OPENTABLEstart : tablename : CONTENT\n            | CONTENT nameskiptag : CONTENT skiptag\n                | OPENHREF skiptag\n                | CLOSEHREF skiptag\n                | handleData : OPENDATA CONTENT OPENHREF CONTENT CLOSEHREF CLOSEDATA skip\n                    | handleRow : OPENROW OPENHEADER skiptag CLOSEHEADER OPENHEADER skiptag CLOSEHEADER OPENHEADER skiptag CLOSEHEADER CLOSEROW handleRow\n                    | OPENROW OPENHEADER OPENHREF CONTENT CLOSEHREF CLOSEHEADER handleData CLOSEROW handleRow\n                    | OPENROW  handleData CLOSEROW handleRow\n                    | skip : OPENDATA skiptag CLOSEDATA skip\n            | table : BEGINTABLE skiptag OPENTABLE handleRow CLOSETABLEempty :content : CONTENT\n               | empty'
    
_lr_action_items = {'BEGINTABLE':([0,],[3,]),'$end':([1,2,14,],[0,-1,-16,]),'CONTENT':([3,5,6,7,15,17,19,23,25,26,27,35,37,],[5,5,5,5,5,21,23,5,28,5,5,5,5,]),'OPENHREF':([3,5,6,7,15,19,21,23,26,27,35,37,],[6,6,6,6,19,6,25,6,6,6,6,6,]),'CLOSEHREF':([3,5,6,7,15,19,23,26,27,28,35,37,],[7,7,7,7,7,7,27,7,7,31,7,7,]),'OPENTABLE':([3,4,5,6,7,9,10,11,],[-7,8,-7,-7,-7,-4,-5,-6,]),'CLOSEHEADER':([5,6,7,9,10,11,15,18,19,23,26,27,29,35,39,],[-7,-7,-7,-4,-5,-6,-7,22,-7,-7,-7,30,32,-7,42,]),'CLOSEDATA':([5,6,7,9,10,11,31,37,41,],[-7,-7,-7,-4,-5,-6,34,-7,43,]),'OPENROW':([8,20,36,44,],[13,13,13,13,]),'CLOSETABLE':([8,12,20,24,36,40,44,46,],[-13,14,-13,-12,-13,-11,-13,-10,]),'OPENHEADER':([13,22,32,],[15,26,35,]),'OPENDATA':([13,30,34,43,],[17,17,37,37,]),'CLOSEROW':([13,16,30,33,34,38,42,43,45,],[-9,20,-9,36,-15,-8,44,-15,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,5,6,7,15,19,23,26,27,35,37,],[4,9,10,11,18,10,9,29,11,39,41,]),'handleRow':([8,20,36,44,],[12,24,40,46,]),'handleData':([13,30,],[16,33,]),'skip':([34,43,],[38,45,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','teams.py',101),
  ('name -> CONTENT','name',1,'p_name','teams.py',104),
  ('name -> CONTENT name','name',2,'p_name','teams.py',105),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','teams.py',112),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','teams.py',113),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','teams.py',114),
  ('skiptag -> <empty>','skiptag',0,'p_skiptag','teams.py',115),
  ('handleData -> OPENDATA CONTENT OPENHREF CONTENT CLOSEHREF CLOSEDATA skip','handleData',7,'p_handleData','teams.py',117),
  ('handleData -> <empty>','handleData',0,'p_handleData','teams.py',118),
  ('handleRow -> OPENROW OPENHEADER skiptag CLOSEHEADER OPENHEADER skiptag CLOSEHEADER OPENHEADER skiptag CLOSEHEADER CLOSEROW handleRow','handleRow',12,'p_handle_row','teams.py',123),
  ('handleRow -> OPENROW OPENHEADER OPENHREF CONTENT CLOSEHREF CLOSEHEADER handleData CLOSEROW handleRow','handleRow',9,'p_handle_row','teams.py',124),
  ('handleRow -> OPENROW handleData CLOSEROW handleRow','handleRow',4,'p_handle_row','teams.py',125),
  ('handleRow -> <empty>','handleRow',0,'p_handle_row','teams.py',126),
  ('skip -> OPENDATA skiptag CLOSEDATA skip','skip',4,'p_skip','teams.py',129),
  ('skip -> <empty>','skip',0,'p_skip','teams.py',130),
  ('table -> BEGINTABLE skiptag OPENTABLE handleRow CLOSETABLE','table',5,'p_table','teams.py',132),
  ('empty -> <empty>','empty',0,'p_empty','teams.py',136),
  ('content -> CONTENT','content',1,'p_content','teams.py',139),
  ('content -> empty','content',1,'p_content','teams.py',140),
]
